#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""功能数据模块 - 集中定义所有运维工具的功能元数据"""
from modules import network, system, cleanup, boot, optimize, info, tools

FUNCTIONS = [
    # 网络修复
    {"id": "flush_dns", "name": "刷新 DNS 缓存", "desc": "清理系统DNS缓存，解决DNS缓存过多/过期导致无法访问网页的问题", "category": "network", "icon": "🌐", "func": network.flush_dns, "danger": False, "admin": True, "reboot": False},
    {"id": "renew_dns_dhcp", "name": "DNS 设为自动获取", "desc": "将所有网络适配器的DNS服务器设置为自动获取", "category": "network", "icon": "🌐", "func": network.renew_dns_dhcp, "danger": False, "admin": True, "reboot": False},
    {"id": "release_renew_ip", "name": "释放并更新 IP", "desc": "释放当前IP并重新从DHCP服务器获取，解决IP冲突、获取不到IP等问题", "category": "network", "icon": "🌐", "func": network.release_renew_ip, "danger": False, "admin": True, "reboot": False},
    {"id": "reset_winsock", "name": "重置 Winsock", "desc": "重置Windows网络协议栈，解决网络相关DLL损坏或配置错误", "category": "network", "icon": "🌐", "func": network.reset_winsock, "danger": True, "admin": True, "reboot": True},
    {"id": "reset_tcpip", "name": "重置 TCP/IP", "desc": "重置TCP/IP协议栈到安装时的默认状态", "category": "network", "icon": "🌐", "func": network.reset_tcpip, "danger": True, "admin": True, "reboot": True},
    {"id": "clear_arp", "name": "清除 ARP 缓存", "desc": "清除ARP地址解析协议缓存，解决局域网内IP-MAC映射错误", "category": "network", "icon": "🌐", "func": network.clear_arp, "danger": False, "admin": True, "reboot": False},
    {"id": "reset_firewall", "name": "重置防火墙", "desc": "将Windows防火墙恢复为默认设置，所有自定义规则将丢失", "category": "network", "icon": "🌐", "func": network.reset_firewall, "danger": True, "admin": True, "reboot": False},
    {"id": "reset_network_full", "name": "一键网络重置", "desc": "依次执行所有网络修复操作，解决大部分网络连接问题", "category": "network", "icon": "🌐", "func": network.reset_network_full, "danger": True, "admin": True, "reboot": True},
    # 系统修复
    {"id": "sfc_scannow", "name": "SFC 系统文件检查", "desc": "扫描并修复损坏的Windows系统文件", "category": "system", "icon": "🛠", "func": system.sfc_scannow, "danger": False, "admin": True, "reboot": False},
    {"id": "dism_check_health", "name": "DISM 检查映像健康", "desc": "检查Windows系统映像是否完整健康", "category": "system", "icon": "🛠", "func": system.dism_check_health, "danger": False, "admin": True, "reboot": False},
    {"id": "dism_scan_health", "name": "DISM 扫描映像", "desc": "深度扫描系统映像文件", "category": "system", "icon": "🛠", "func": system.dism_scan_health, "danger": False, "admin": True, "reboot": False},
    {"id": "dism_restore_health", "name": "DISM 修复映像", "desc": "从Windows Update下载并修复系统映像", "category": "system", "icon": "🛠", "func": system.dism_restore_health, "danger": True, "admin": True, "reboot": False},
    {"id": "dism_full_repair", "name": "完整 SFC+DISM 修复", "desc": "依次执行DISM检查/扫描/修复 + SFC，彻底修复系统", "category": "system", "icon": "🛠", "func": system.dism_full_repair, "danger": True, "admin": True, "reboot": False},
    {"id": "chkdsk_system_drive", "name": "检查 C 盘文件系统", "desc": "检查C盘文件系统是否有错误（只读模式）", "category": "system", "icon": "🛠", "func": system.chkdsk_system_drive, "danger": False, "admin": True, "reboot": False},
    {"id": "chkdsk_fix", "name": "修复 C 盘文件系统", "desc": "计划在下次重启时检查并修复C盘文件系统错误", "category": "system", "icon": "🛠", "func": system.chkdsk_fix, "danger": True, "admin": True, "reboot": True},
    {"id": "create_restore_point", "name": "创建系统还原点", "desc": "创建系统还原点，以便出现问题时可以回滚", "category": "system", "icon": "🛠", "func": system.create_restore_point, "danger": False, "admin": True, "reboot": False},
    {"id": "repair_windows_update", "name": "修复 Windows Update", "desc": "重置Windows Update组件，解决更新失败、卡住等问题", "category": "system", "icon": "🛠", "func": system.repair_windows_update, "danger": True, "admin": True, "reboot": False},
    # 清理工具
    {"id": "clean_temp_files", "name": "清理系统临时文件", "desc": "清理 %TEMP%、%TMP%、C:\\Windows\\Temp 等临时文件夹", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_temp_files, "danger": False, "admin": False, "reboot": False},
    {"id": "clean_windows_update_cache", "name": "清理 Windows Update 缓存", "desc": "清理C:\\Windows\\SoftwareDistribution\\Download，可释放数GB空间", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_windows_update_cache, "danger": False, "admin": True, "reboot": False},
    {"id": "clean_recycle_bin", "name": "清空回收站", "desc": "清空所有磁盘分区的回收站", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_recycle_bin, "danger": False, "admin": True, "reboot": False},
    {"id": "disable_hibernate", "name": "关闭休眠释放空间", "desc": "关闭休眠并删除hiberfil.sys，释放与内存等量的磁盘空间", "category": "cleanup", "icon": "🧹", "func": cleanup.disable_hibernate, "danger": True, "admin": True, "reboot": False},
    {"id": "clean_windows_old", "name": "清理 Windows.old", "desc": "删除Windows大版本升级后的旧系统备份（不可逆）", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_windows_old, "danger": True, "admin": True, "reboot": False},
    {"id": "clean_browser_cache", "name": "清理浏览器缓存", "desc": "清理Chrome、Edge、Firefox浏览器的缓存文件", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_browser_cache, "danger": False, "admin": False, "reboot": False},
    {"id": "clean_dns_cache", "name": "清理 DNS 缓存", "desc": "刷新DNS解析缓存", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_dns_cache, "danger": False, "admin": True, "reboot": False},
    {"id": "clean_thumbnail_cache", "name": "清理缩略图缓存", "desc": "清理资源管理器的缩略图缓存文件", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_thumbnail_cache, "danger": False, "admin": True, "reboot": False},
    {"id": "clean_prefetch", "name": "清理预读取文件", "desc": "清理C:\\Windows\\Prefetch下的预读取文件", "category": "cleanup", "icon": "🧹", "func": cleanup.clean_prefetch, "danger": False, "admin": True, "reboot": False},
    {"id": "disk_cleanup_wizard", "name": "磁盘清理向导", "desc": "打开Windows自带的磁盘清理工具", "category": "cleanup", "icon": "🧹", "func": cleanup.disk_cleanup_wizard, "danger": False, "admin": False, "reboot": False},
    {"id": "scan_large_files", "name": "扫描 C 盘大文件", "desc": "扫描C盘中大于100MB的文件，帮助找出占用空间的大文件", "category": "cleanup", "icon": "🧹", "func": cleanup.scan_large_files, "danger": False, "admin": False, "reboot": False},
    {"id": "analyze_disk_usage", "name": "分析 C 盘空间使用", "desc": "分析C盘各主要目录的磁盘占用情况", "category": "cleanup", "icon": "🧹", "func": cleanup.analyze_disk_usage, "danger": False, "admin": False, "reboot": False},
    {"id": "full_cleanup", "name": "一键全面清理", "desc": "一键执行所有常规清理操作", "category": "cleanup", "icon": "🧹", "func": cleanup.full_cleanup, "danger": True, "admin": True, "reboot": False},
    # 开机修复
    {"id": "fix_mbr", "name": "修复 MBR", "desc": "重写主引导记录，解决因MBR损坏导致的无法开机", "category": "boot", "icon": "🔧", "func": boot.fix_mbr, "danger": True, "admin": True, "reboot": True},
    {"id": "fix_boot", "name": "修复引导扇区", "desc": "修复系统引导扇区，解决BOOTMGR丢失问题", "category": "boot", "icon": "🔧", "func": boot.fix_boot, "danger": True, "admin": True, "reboot": True},
    {"id": "rebuild_bcd", "name": "重建 BCD", "desc": "重建BCD引导配置数据，解决引导菜单损坏或丢失", "category": "boot", "icon": "🔧", "func": boot.rebuild_bcd, "danger": True, "admin": True, "reboot": True},
    {"id": "fix_boot_full", "name": "完整引导修复", "desc": "一键修复MBR+引导扇区+BCD", "category": "boot", "icon": "🔧", "func": boot.fix_boot_full, "danger": True, "admin": True, "reboot": True},
    {"id": "disable_fast_startup", "name": "禁用快速启动", "desc": "关闭快速启动，解决关机后无法正常开机、驱动异常等问题", "category": "boot", "icon": "🔧", "func": boot.disable_fast_startup, "danger": True, "admin": True, "reboot": False},
    {"id": "enable_safe_mode", "name": "下次进入安全模式", "desc": "配置下次重启进入安全模式，用于排查问题", "category": "boot", "icon": "🔧", "func": boot.enable_safe_mode_boot, "danger": True, "admin": True, "reboot": True},
    {"id": "enable_safe_mode_network", "name": "带网络安全模式", "desc": "安全模式下可联网，方便下载驱动或修复工具", "category": "boot", "icon": "🔧", "func": boot.enable_safe_mode_network, "danger": True, "admin": True, "reboot": True},
    {"id": "disable_safe_mode", "name": "取消安全模式", "desc": "取消安全模式设置，恢复正常启动", "category": "boot", "icon": "🔧", "func": boot.disable_safe_mode, "danger": False, "admin": True, "reboot": False},
    {"id": "check_startup_items", "name": "查看开机启动项", "desc": "查看注册表和启动文件夹中的开机自启程序", "category": "boot", "icon": "🔧", "func": boot.check_startup_items, "danger": False, "admin": False, "reboot": False},
    {"id": "check_boot_config", "name": "查看引导配置", "desc": "使用bcdedit查看当前系统引导配置详情", "category": "boot", "icon": "🔧", "func": boot.check_boot_config, "danger": False, "admin": True, "reboot": False},
    {"id": "fix_black_screen", "name": "修复开机黑屏", "desc": "综合修复开机后黑屏/无显示的问题", "category": "boot", "icon": "🔧", "func": boot.fix_black_screen, "danger": True, "admin": True, "reboot": True},
    {"id": "fix_boot_loop", "name": "修复循环重启", "desc": "修复Windows开机后反复重启的故障", "category": "boot", "icon": "🔧", "func": boot.fix_boot_loop, "danger": True, "admin": True, "reboot": True},
    {"id": "fix_explorer_startup", "name": "修复资源管理器不启动", "desc": "修复开机后桌面/任务栏不显示的问题", "category": "boot", "icon": "🔧", "func": boot.fix_explorer_startup, "danger": False, "admin": True, "reboot": False},
    # 性能优化
    {"id": "set_high_performance", "name": "高性能电源模式", "desc": "设置为高性能电源计划，让CPU始终以最高频率运行", "category": "optimize", "icon": "⚡", "func": optimize.set_high_performance_power, "danger": False, "admin": True, "reboot": False},
    {"id": "set_balanced_power", "name": "平衡电源模式", "desc": "恢复为Windows默认的平衡电源计划", "category": "optimize", "icon": "⚡", "func": optimize.set_balanced_power, "danger": False, "admin": True, "reboot": False},
    {"id": "set_power_saver", "name": "节能电源模式", "desc": "切换到节能模式，降低功耗但可能影响性能", "category": "optimize", "icon": "⚡", "func": optimize.set_power_saver, "danger": False, "admin": True, "reboot": False},
    {"id": "disable_visual_effects", "name": "最佳性能视觉效果", "desc": "关闭窗口动画、阴影等视觉效果，提升系统流畅度", "category": "optimize", "icon": "⚡", "func": optimize.disable_visual_effects, "danger": False, "admin": True, "reboot": False},
    {"id": "enable_visual_effects", "name": "恢复默认视觉效果", "desc": "恢复Windows默认的视觉效果设置", "category": "optimize", "icon": "⚡", "func": optimize.enable_visual_effects, "danger": False, "admin": True, "reboot": False},
    {"id": "memory_diagnostic", "name": "内存诊断工具", "desc": "启动Windows内存诊断工具，检查内存条是否有故障", "category": "optimize", "icon": "⚡", "func": optimize.memory_diagnostic, "danger": False, "admin": True, "reboot": True},
    {"id": "check_virtual_memory", "name": "检查虚拟内存", "desc": "查看当前虚拟内存(pagefile)的配置情况", "category": "optimize", "icon": "⚡", "func": optimize.check_virtual_memory, "danger": False, "admin": True, "reboot": False},
    {"id": "set_virtual_memory_auto", "name": "虚拟内存自动管理", "desc": "让系统自动管理虚拟内存大小", "category": "optimize", "icon": "⚡", "func": optimize.set_virtual_memory_auto, "danger": False, "admin": True, "reboot": False},
    {"id": "optimize_ssd", "name": "SSD TRIM 优化", "desc": "对固态硬盘执行TRIM命令，保持SSD读写性能", "category": "optimize", "icon": "⚡", "func": optimize.optimize_ssd, "danger": False, "admin": True, "reboot": False},
    {"id": "defrag_analysis", "name": "分析磁盘碎片", "desc": "分析机械硬盘的碎片率，判断是否需要碎片整理", "category": "optimize", "icon": "⚡", "func": optimize.defrag_analysis, "danger": False, "admin": True, "reboot": False},
    {"id": "defrag_disk", "name": "磁盘碎片整理", "desc": "整理机械硬盘碎片（SSD请勿使用）", "category": "optimize", "icon": "⚡", "func": optimize.defrag_disk, "danger": True, "admin": True, "reboot": False},
    {"id": "check_disk_performance", "name": "检查磁盘健康", "desc": "查看各磁盘的SMART健康状态", "category": "optimize", "icon": "⚡", "func": optimize.check_disk_performance, "danger": False, "admin": True, "reboot": False},
    {"id": "check_cpu_info", "name": "查看 CPU 信息", "desc": "查看CPU型号、核心数、当前负载", "category": "optimize", "icon": "⚡", "func": optimize.check_cpu_info, "danger": False, "admin": False, "reboot": False},
    {"id": "check_memory_info", "name": "查看内存信息", "desc": "查看物理内存条容量、频率、制造商", "category": "optimize", "icon": "⚡", "func": optimize.check_memory_info, "danger": False, "admin": False, "reboot": False},
    {"id": "performance_tuning_full", "name": "一键全面性能优化", "desc": "一键执行所有性能优化操作", "category": "optimize", "icon": "⚡", "func": optimize.performance_tuning_full, "danger": True, "admin": True, "reboot": False},
    # 系统信息
    {"id": "get_system_full_info", "name": "完整系统信息", "desc": "查看CPU、主板、BIOS、内存、磁盘、显卡、网卡的详细信息", "category": "info", "icon": "📊", "func": info.get_system_full_info, "danger": False, "admin": False, "reboot": False},
    {"id": "get_os_version", "name": "操作系统版本", "desc": "查看Windows版本、构建号、架构、安装日期", "category": "info", "icon": "📊", "func": info.get_os_version, "danger": False, "admin": False, "reboot": False},
    {"id": "get_disk_usage_info", "name": "磁盘使用情况", "desc": "查看各磁盘分区的使用率和剩余空间", "category": "info", "icon": "📊", "func": info.get_disk_usage, "danger": False, "admin": False, "reboot": False},
    {"id": "get_network_info", "name": "网络配置信息", "desc": "查看IP配置、DNS服务器、DNS缓存条目数", "category": "info", "icon": "📊", "func": info.get_network_info, "danger": False, "admin": False, "reboot": False},
    {"id": "get_recent_errors", "name": "最近系统错误", "desc": "查看最近的系统级错误，帮助定位蓝屏/死机原因", "category": "info", "icon": "📊", "func": info.get_recent_errors, "danger": False, "admin": True, "reboot": False},
    {"id": "get_application_errors", "name": "最近应用错误", "desc": "查看最近的应用程序崩溃/错误", "category": "info", "icon": "📊", "func": info.get_application_errors, "danger": False, "admin": True, "reboot": False},
    {"id": "get_hotfix_info", "name": "已安装 Windows 更新", "desc": "查看系统已安装的补丁和更新列表", "category": "info", "icon": "📊", "func": info.get_hotfix_info, "danger": False, "admin": True, "reboot": False},
    {"id": "get_driver_info", "name": "驱动信息", "desc": "查看系统已安装的驱动程序列表", "category": "info", "icon": "📊", "func": info.get_driver_info, "danger": False, "admin": True, "reboot": False},
    {"id": "get_running_services", "name": "运行中的第三方服务", "desc": "查看非Microsoft的正在运行的服务", "category": "info", "icon": "📊", "func": info.get_running_services, "danger": False, "admin": True, "reboot": False},
    {"id": "get_installed_software", "name": "已安装软件列表", "desc": "查看通过Windows Installer安装的软件", "category": "info", "icon": "📊", "func": info.get_installed_software, "danger": False, "admin": True, "reboot": False},

    # 系统工具
    {"id": "open_task_manager", "name": "任务管理器", "desc": "打开 Windows 任务管理器，查看进程、性能和资源占用", "category": "tools", "icon": "🧰", "func": tools.open_task_manager, "danger": False, "admin": False, "reboot": False},
    {"id": "open_event_viewer", "name": "事件查看器", "desc": "查看系统、应用程序和安全事件日志", "category": "tools", "icon": "🧰", "func": tools.open_event_viewer, "danger": False, "admin": False, "reboot": False},
    {"id": "open_registry_editor", "name": "注册表编辑器", "desc": "打开注册表编辑器，修改系统高级配置", "category": "tools", "icon": "🧰", "func": tools.open_registry_editor, "danger": True, "admin": True, "reboot": False},
    {"id": "open_services", "name": "服务管理", "desc": "管理系统后台服务的启动和停止", "category": "tools", "icon": "🧰", "func": tools.open_services, "danger": False, "admin": False, "reboot": False},
    {"id": "open_disk_management", "name": "磁盘管理", "desc": "管理磁盘分区、卷和驱动器号", "category": "tools", "icon": "🧰", "func": tools.open_disk_management, "danger": False, "admin": True, "reboot": False},
    {"id": "open_device_manager", "name": "设备管理器", "desc": "查看和管理硬件设备驱动", "category": "tools", "icon": "🧰", "func": tools.open_device_manager, "danger": False, "admin": False, "reboot": False},
    {"id": "open_network_connections", "name": "网络连接", "desc": "查看和管理网络适配器", "category": "tools", "icon": "🧰", "func": tools.open_network_connections, "danger": False, "admin": False, "reboot": False},
    {"id": "open_system_properties", "name": "系统属性", "desc": "打开系统属性，查看计算机名、硬件和系统保护", "category": "tools", "icon": "🧰", "func": tools.open_system_properties, "danger": False, "admin": False, "reboot": False},
    {"id": "open_firewall", "name": "防火墙设置", "desc": "打开 Windows Defender 防火墙", "category": "tools", "icon": "🧰", "func": tools.open_firewall, "danger": False, "admin": False, "reboot": False},
    {"id": "open_power_options", "name": "电源选项", "desc": "管理电源计划和节能设置", "category": "tools", "icon": "🧰", "func": tools.open_power_options, "danger": False, "admin": False, "reboot": False},
]
